spring:
  h2:
    console:
      enabled: true
      path: /game-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:game-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: gameadmin
    password: gamepwd
    driver-class-name: org.h2.Driver
server:
  port: 9090